
#define MENUID_SETTINGS 40004
#define MENUID_EXIT     40003
#define MENUID_NEWGAME  40001
#define MENUID_UNDO     40002
#define MENUID_SAVE     40005
#define MENUID_SAVEAS   40006
#define MENUID_LOAD     40007
#define MENUID_OPEN     40008

#define IDC_SETTINGS_THINKDEPTH      1
#define IDC_SETTINGS_THINKDEPTH_SPIN 2
#define IDC_SETTINGS_OK              3
#define IDC_SETTINGS_CANCEL          4

#define IDC_NEWGAME_WIDTH       1
#define IDC_NEWGAME_WIDTH_SPIN  2
#define IDC_NEWGAME_HEIGHT      3
#define IDC_NEWGAME_HEIGHT_SPIN 4
#define IDC_NEWGAME_START       5
#define IDC_NEWGAME_CANCEL      6

